const INVALID_PATCH_DATA = -1;
const INVALID_QUERY_STRING = -2;
const PAGE_NOT_FOUND = -3;

const USER_NOT_FOUND = -100;
const USERNAME_ALREADY_EXISTS = -101;
const INCORRECT_USERNAME_PASSWORD = -102;
const EMAIL_NOT_VERIFIED = -103;
const PERMISSION_NOT_GRANTED = -104;
const INVALID_USER_ROLE = -105;
const INVALID_AUTH_DATA = -106;
const AUTHORIZATION_FAILED = -107;
const INVALID_USER_TYPE = -108;
const INSTRUCTOR_NOT_IN_COURSE = -109;
const EMAIL_ALREADY_EXISTS = -110;
const INVALID_SIGNUP_DATA = -111;

const INVALID_COURSE_DATA = -200;
const COURSE_NOT_FOUND = -201;
const SECTION_NOT_FOUND = -202;
const COURSE_ACCESS_DENIED = -203;
const INVALID_SECTION_DATA = -204;
const INVALID_QUIZ_DATA = -205;
const INVALID_MODULE_DATA = -206;
const QUIZ_NOT_FOUND = -207;
const MODULE_NOT_FOUND = -208;
const QUESTION_NOT_FOUND = -209;
const UNPURCHASABLE_COURSE = -210;
const COURSE_NOT_FREE = -211;
const SLUG_ALREADY_EXISTS = -212;
const TEACHING_ALREADY_EXISTS = -213;
const COURSE_NOT_ENROLLABLE = -214;
const CHOICE_NOT_FOUND = -215;
const COURSE_NOT_AVAILABLE = -216;
const MODULE_NOT_AVAILABLE = -217;

const INVALID_ENROLLMENT_DATA = -300;
const ENROLLMENT_NOT_FOUND = -301;
const ENROLLMENT_ALREADY_EXISTS = -302;

const CATEGORY_NOT_FOUND = -400;
const INVALID_CATEGORY_DATA = -401;
const CATEGORY_ALREADY_EXISTS = -403;

const INVALID_FEEDBACK_DATA = -500;
const FEEDBACK_ALREADY_EXISTS = -501;
const FEEDBACK_ACCESS_DENIED = -502;
const FEEDBACK_NOT_FOUND = -503;

const INVALID_ORDER_DATA = -600;

const SEMESTER_ALREADY_EXISTS = -700;
const SEMESTER_NOT_FOUND = -701;
const INVALID_SEMESTER_DATA = -702;

export const ServerErrors = {
    INVALID_PATCH_DATA,
    INVALID_QUERY_STRING,
    PAGE_NOT_FOUND,

    USER_NOT_FOUND,
    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    INCORRECT_USERNAME_PASSWORD,
    EMAIL_NOT_VERIFIED,
    PERMISSION_NOT_GRANTED,
    INVALID_USER_TYPE,
    INVALID_AUTH_DATA,
    AUTHORIZATION_FAILED,
    INVALID_USER_ROLE,
    INSTRUCTOR_NOT_IN_COURSE,
    INVALID_SIGNUP_DATA,

    INVALID_COURSE_DATA,
    COURSE_NOT_FOUND,
    UNPURCHASABLE_COURSE,
    SECTION_NOT_FOUND,
    INVALID_SECTION_DATA,
    INVALID_QUIZ_DATA,
    INVALID_MODULE_DATA,
    QUIZ_NOT_FOUND,
    MODULE_NOT_FOUND,
    QUESTION_NOT_FOUND,
    CHOICE_NOT_FOUND,
    COURSE_ACCESS_DENIED,
    COURSE_NOT_FREE,
    SLUG_ALREADY_EXISTS,
    TEACHING_ALREADY_EXISTS,
    COURSE_NOT_ENROLLABLE,
    COURSE_NOT_AVAILABLE,
    MODULE_NOT_AVAILABLE,

    INVALID_ENROLLMENT_DATA,
    ENROLLMENT_NOT_FOUND,
    ENROLLMENT_ALREADY_EXISTS,

    CATEGORY_NOT_FOUND,
    INVALID_CATEGORY_DATA,
    CATEGORY_ALREADY_EXISTS,

    INVALID_FEEDBACK_DATA,
    FEEDBACK_ALREADY_EXISTS,
    FEEDBACK_ACCESS_DENIED,
    FEEDBACK_NOT_FOUND,

    INVALID_ORDER_DATA,

    SEMESTER_ALREADY_EXISTS,
    SEMESTER_NOT_FOUND,
    INVALID_SEMESTER_DATA
};
