const INVALID_PATCH_DATA = -1;
const INVALID_QUERY_STRING = -2;
const PAGE_NOT_FOUND = -3;

const USER_NOT_FOUND = -100;
const USERNAME_ALREADY_EXISTS = -101;
const INCORRECT_USERNAME_PASSWORD = -102;
const EMAIL_NOT_VERIFIED = -103;
const EMAIL_VERIFICATION_FAILED = -104;
const PERMISSION_NOT_GRANTED = -105;
const ROLE_NOT_GRANTED = -109;
const INVALID_AUTH_DATA = -106;
const AUTHORIZATION_FAILED = -107;
const INVALID_USER_TYPE = -108;
const INSTRUCTOR_NOT_IN_COURSE = -109;
const EMAIL_ALREADY_EXISTS = -110;

const INVALID_COURSE_DATA = -200;
const COURSE_NOT_FOUND = -201;
const SECTION_NOT_FOUND = -202;
const NO_ACCESS_TO_COURSE = -203;
const INVALID_SECTION_DATA = -204;
const INVALID_QUIZ_DATA = -205;
const INVALID_MODULE_DATA = -206;
const QUIZ_NOT_FOUND = -207;
const MODULE_NOT_FOUND = -208;
const QUESTION_NOT_FOUND = -209;

const INVALID_ENROLLMENT_DATA = -300;
const ENROLLMENT_NOT_FOUND = -301;
const ENROLLMENT_ALREADY_EXIST = -302;
const ENROLLMENT_ALREADY_ACTIVE = -303;

const CATEGORY_NOT_FOUND = -400;
const INVALID_CATEGORY_DATA = -401;
const CATEGORY_ALREADY_EXISTS = -403;

const INVALID_FEEDBACK_DATA = -500;
const FEEDBACK_ALREADY_EXISTS = -501;
const NO_ACCESS_TO_FEEDBACK = -502;
const FEEDBACK_NOT_FOUND = -503;

export const ServerErrors = {
    INVALID_PATCH_DATA,
    INVALID_QUERY_STRING,
    PAGE_NOT_FOUND,

    USER_NOT_FOUND,
    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    INCORRECT_USERNAME_PASSWORD,
    EMAIL_NOT_VERIFIED,
    EMAIL_VERIFICATION_FAILED,
    PERMISSION_NOT_GRANTED,
    ROLE_NOT_GRANTED,
    INVALID_AUTH_DATA,
    AUTHORIZATION_FAILED,
    INVALID_USER_TYPE,
    INSTRUCTOR_NOT_IN_COURSE,

    INVALID_COURSE_DATA,
    COURSE_NOT_FOUND,
    SECTION_NOT_FOUND,
    INVALID_SECTION_DATA,
    INVALID_QUIZ_DATA,
    INVALID_MODULE_DATA,
    QUIZ_NOT_FOUND,
    MODULE_NOT_FOUND,
    QUESTION_NOT_FOUND,
    NO_ACCESS_TO_COURSE,

    INVALID_ENROLLMENT_DATA,
    ENROLLMENT_NOT_FOUND,
    ENROLLMENT_ALREADY_EXIST,
    ENROLLMENT_ALREADY_ACTIVE,

    CATEGORY_NOT_FOUND,
    INVALID_CATEGORY_DATA,
    CATEGORY_ALREADY_EXISTS,

    INVALID_FEEDBACK_DATA,
    FEEDBACK_ALREADY_EXISTS,
    NO_ACCESS_TO_FEEDBACK,
    FEEDBACK_NOT_FOUND
};
